### ISSUE TITLE
Kernel 4.2 issue

### ISSUE THREAD

**Issue by tobiasBora** [kuba-moo/mt7630e#20]
Hello,

First thank you for your modifications, they are really great ! With them I manage to get Wifi work on ubuntu 14.04 (everything works like a charme), on Ubuntu 15.04 (only wifi works), and on Debian 8 (wifi + bluetooth).

However, I downloaded today Debian Testing, that uses a kernel 4.2. The problem now is that the driver doesn't even compile... I got the error:

```
error: ‘FIF_PROMISC_IN_BSS’ undeclared (first use in this function)
```

Could you please help me solving it ? If you want I can provide you any testing you want. I really need it, and I already spend hours on that problem...

Thank you in advance,

TobiasBora

PS: Here is the whole error:

```
$ make
make -C /lib/modules/`uname -r`/build M=/home/leo/Logiciels/Bidouille/carte_wifi/kernel_1.9/wifi_only/test_kuba_moo/mt7630e/rt2x00 modules
make[1]: Entering directory '/usr/src/linux-headers-4.2.0-1-amd64'
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
  CC [M]  /home/leo/Logiciels/Bidouille/carte_wifi/kernel_1.9/wifi_only/test_kuba_moo/mt7630e/rt2x00/rt2x00mac.o
/home/leo/Logiciels/Bidouille/carte_wifi/kernel_1.9/wifi_only/test_kuba_moo/mt7630e/rt2x00/rt2x00mac.c: In function ‘rt2x00mac_configure_filter’:
/home/leo/Logiciels/Bidouille/carte_wifi/kernel_1.9/wifi_only/test_kuba_moo/mt7630e/rt2x00/rt2x00mac.c:359:6: error: ‘FIF_PROMISC_IN_BSS’ undeclared (first use in this function)
      FIF_PROMISC_IN_BSS;
      ^
/home/leo/Logiciels/Bidouille/carte_wifi/kernel_1.9/wifi_only/test_kuba_moo/mt7630e/rt2x00/rt2x00mac.c:359:6: note: each undeclared identifier is reported only once for each function it appears in
/usr/src/linux-headers-4.2.0-1-common/scripts/Makefile.build:263: recipe for target '/home/leo/Logiciels/Bidouille/carte_wifi/kernel_1.9/wifi_only/test_kuba_moo/mt7630e/rt2x00/rt2x00mac.o' failed
make[4]: *** [/home/leo/Logiciels/Bidouille/carte_wifi/kernel_1.9/wifi_only/test_kuba_moo/mt7630e/rt2x00/rt2x00mac.o] Error 1
/usr/src/linux-headers-4.2.0-1-common/Makefile:1403: recipe for target '_module_/home/leo/Logiciels/Bidouille/carte_wifi/kernel_1.9/wifi_only/test_kuba_moo/mt7630e/rt2x00' failed
make[3]: *** [_module_/home/leo/Logiciels/Bidouille/carte_wifi/kernel_1.9/wifi_only/test_kuba_moo/mt7630e/rt2x00] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.2.0-1-amd64'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by neurobin** [comment]
If you want you can use [my version of the driver](https://github.com/neurobin/MT7630E). It can be installed with kernel upto 4.2*. The bluetooth problem still persists though...

**Comment by tobiasBora** [comment]
The problem was that I need to run the Makefile in sudo (Even in your script Neurobin, I need to do "sudo make clean" not to have this error). Problem solved, but the bluetooth is still an issue...

**Comment by JaewooKim0** [comment]
How about doing pull request to kuba-moo's repository with benjarobin's patch?
It seems that kuba-moo is working with Linux Wireless(at kernel.org), so merging every efforts to this repository would be good.
Maybe benjarobin himself could do this, because he is the author of the patch.
hmm.. I'll try to tell him with my poor English. : )
